services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dw
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass!123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always

volumes:
  sqlserver-data:
